// <auto-generated />
using Infrastructure.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WorkerService.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Student")
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentId");

                    b.ToTable("Students", "Student");

                    b.HasData(
                        new
                        {
                            StudentId = "1",
                            Age = 32,
                            Course = "C#",
                            Name = "이건우"
                        },
                        new
                        {
                            StudentId = "2",
                            Age = 32,
                            Course = "JAVA",
                            Name = "안성윤"
                        },
                        new
                        {
                            StudentId = "3",
                            Age = 32,
                            Course = "JAVASCRIPT",
                            Name = "장동계"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
